sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
notifications:
  slack: mindmapsdb:3M1bWW0kGQ7LdniMmKeaY3o5
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report